Vote_of_LeeLab/Vote_of_LeeLab/urls.py
"""
Definition of urls for Vote_of_LeeLab.
"""

from datetime import datetime
from django.conf.urls import url, handler400, handler403, handler404, handler500
from django.contrib.staticfiles.views import serve
import django.contrib.auth.views

import VoteApp.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

handler400 = 'VoteApp.views.handler400'
handler403 = 'VoteApp.views.handler403'
handler404 = 'VoteApp.views.handler404'
handler500 = 'VoteApp.views.handler500'

urlpatterns = [
    # Examples:
    url(r'^$', VoteApp.views.index, name='index'),
    url(r'^about$', VoteApp.views.about, name='about'),
    url(r'^camera$', VoteApp.views.camera, name='camera'),
    url(r'^candidate$', VoteApp.views.candidate, name='candidate'),
    # url(r'^candidate/(?P<pk>\w+)$', VoteApp.views.candidate, name='candidate'),
    url(r'^vote$', VoteApp.views.vote, name='vote'),
    url(r'^result$', VoteApp.views.result, name='result'),
    url(r'^capstone_design$', VoteApp.views.capstone, name='capstone'),
    # url(r'^signup$', VoteApp.views.signup, name='signup'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'VoteApp/login.html',
            'authentication_form': VoteApp.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # if DEBUG set False, it needs.
    url(r'^static/(?P<path>.*)$', serve, kwargs={'insecure': True}),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', admin.site.urls),

     # Social Login
     url('', include('social_django.urls', namespace='social')),

     # Like & Dislike
     url(r'^like/$', VoteApp.views.like, name='like'),
     url(r'^like_anonymous/$', VoteApp.views.like_anonymous, name='like_anonymous'),
     url(r'^like_ready/$', VoteApp.views.like_ready, name='like_ready'),
     url(r'^like_result/$', VoteApp.views.like_result, name='like_result'),

    # FCM
    url(r'', include('fcm.urls')),
]

Vote_of_LeeLab/VoteApp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.utils import timezone

class VoteDate(models.Model):
    start_date = models.DateTimeField(default=timezone.now())
    end_date = models.DateTimeField(default=(timezone.datetime.now()+timezone.timedelta(days=7))-timezone.timedelta(seconds=1))


class VoteResult(models.Model):
    '''
    DB 시작/종료일, 투표결과를 저장하는 DB를 만들어야 함.
    설계를 해야 하는데 누군가의 도움을 받아야 할 것으로 생각됨.
    따라서 이 부분은 개발일정을 잠정 중단.
    '''
    vote_id = models.ForeignKey(VoteDate, on_delete=models.CASCADE)
    # player = models.ManyToOneRel



class Like(models.Model):
    name_id = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=8, db_column='이름')
    description = models.CharField(max_length=30, db_column='소개')
    isVote = models.BooleanField(default=False, db_column='후보')
    prize = models.BooleanField(db_column='우승이력', default=False)
    likes = models.ManyToManyField(User, null=True, blank=True, related_name='likes')

    @property
    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        super(Like, self).save(*args, **kwargs)


class Rtsp(models.Model):
    url = models.CharField(max_length=300)

Vote_of_LeeLab/VoteApp/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from .models import Like

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Username or ID'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))


class LikeForm(forms.ModelForm):
    class Meta:
        model = Like
        fields = ['name_id', 'name', 'description']
        widgets = {
            # 'name_id' : forms.TextInput(attrs={'class': 'form-control readonly'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '후보자의 이름을 정해주세요.'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '투표 페이지에 나타낼 메세지를 입력하세요.'}),
        }
        labels = {
            'name_id': 'No',
            'name': '후보자 이름',
            'description': '후보자 소개'
        }

    def __init__(self, *args, **kwargs):
        super(LikeForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['maxlength'] = 8
        self.fields['description'].widget.attrs['maxlength'] = 30


    def merge_from_initial(self):
        filt = lambda v: v not in self.data.keys()
        for field in filter(filt, getattr(self.Meta, 'fields', ())):
            self.data[field] = self.initial.get(field, None)

Vote_of_LeeLab/VoteApp/views.py
from django.shortcuts import render, redirect
import datetime, locale

# Like and Dislike
# https://wayhome25.github.io/django/2017/03/01/django-99-my-first-project-4/
try:
    from django.utils import simplejson as json
except ImportError:
    import json
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from .models import Like, VoteDate, Rtsp
from .forms import LikeForm
from django.db.models import Count
from django.utils import timezone

# Registrator of user
from .forms import BootstrapAuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.

# CountDown
# Windows에서 개발 시 locale 설정, Unix 시스템에 배포 시 반드시 주석처리 할 것.
#locale.setlocale(locale.LC_CTYPE, 'korean')

def index(request):
    '''
    [index page]
    "if" is before start time,
    "elif" is after start time and before end time
    "else" is after end time
    '''
    COUNTDOWN_TARGET_DATE = VoteDate.objects.get(pk=1).start_date
    DURIONG_DATE = VoteDate.objects.get(pk=1).end_date - VoteDate.objects.get(pk=1).start_date

    if COUNTDOWN_TARGET_DATE > timezone.now():
        td = COUNTDOWN_TARGET_DATE - timezone.now()
        send_data = (td.days * 86400) + td.seconds
        return render(
            request,
            "VoteApp/index.html",
           {
               'active_home' : "active", # begin common
               'title' : "투표까지 남은시간",
               'url' : "https://chenny.ml/",
               'description' : "LEE LAB 투표 예정일",
               'sitename' : "Lee Lab Server",
               'locale' : "ko_KR",
               'type' : "article", # end common
               'noti_title' : "[시작 알림!!]", # begin noti
               'noti_context' : "투표가 시작되었습니다! 투표를 시작하세요!",
               'noti_img' : "https://chenny.ml/static/img/logo2.png", # end noti
               'date_of_begin_time' : "투표 예정일 : " + COUNTDOWN_TARGET_DATE.strftime('%Y년 %m월 %d일 - %H시 %M분 %S초'),
               'server_time' : send_data,
           }
        )
    elif (COUNTDOWN_TARGET_DATE + DURIONG_DATE) > timezone.now():
        return redirect('/vote')
    else:
        return redirect('/result')


def about(request):
    '''
    [about page]
    now, it's a page of privacy policy
    '''
    return render(
        request,
        "VoteApp/about.html",
        {
            'active_about' : "active",
            'url' : "https://chenny.ml/about/",
            'description' : "LEE LAB 투표 결과",
            'sitename' : "Lee Lab Server",
            'locale' : "ko_KR",
            'type' : "article",
            'title' : "도움말",
            'content' : "테스트 페이지"
        }
    )


def camera(request):
    '''
    [camera page]
    iframe to node.js server
    '''
    url = Rtsp.objects.get(pk=1).url
    return render(
        request,
        "VoteApp/camera.html",
        {
            'url' : "https://chenny.ml/camera/",
            'description' : "CCTV 영상",
            'sitename' : "Lee Lab Server",
            'locale' : "ko_KR",
            'type' : "article",
            'title' : "CCTV 영상",
            'url' : url,
        }
    )


@login_required
def candidate(request):
    COUNTDOWN_TARGET_DATE = VoteDate.objects.get(pk=1).start_date
    DURIONG_DATE = VoteDate.objects.get(pk=1).end_date - VoteDate.objects.get(pk=1).start_date

    if COUNTDOWN_TARGET_DATE > timezone.now():
        excet_value = True
        try:
            data = Like.objects.get(name_id=User.objects.get(username=request.user.get_username()))
            likes = Like.objects.get(pk=data.id)
        except:
            excet_value = False
            return render(
                request,
                'VoteApp/candidate.html',
                {
                    'active_candidate': "active",  # begin common
                    'title': "후보자 전용 페이지",
                    'url': "https://chenny.ml/",
                    'description': "후보자가 아닙니다",
                    'locale': "ko_KR",
                    'type': "article",  # end common
                    'result' : excet_value,
                    'date' : True
                }
            )

        if request.method == "POST":
            form = LikeForm(request.POST, instance=likes)
            if form.is_valid():
                slike = form.save(commit=False)
                slike.generate()
                return redirect('/')
        else:
            form = LikeForm()
            form.merge_from_initial()
            return render(
                request,
                'VoteApp/candidate.html',
                {
                    'active_candidate': "active",  # begin common
                    'title': "후보자 정보수정",
                    'url': "https://chenny.ml/",
                    'description': "후보자 정보수정 페이지",
                    'locale': "ko_KR",
                    'type': "article",  # end common
                    'form': form,
                    'result': excet_value,
                    'likes' : likes,
                    'date': True
                }
            )
    else:
        return render(
            request,
            'VoteApp/candidate.html',
            {
                'active_candidate': "active",  # begin common
                'title': "후보자 정보수정",
                'url': "https://chenny.ml/",
                'description': "후보자 정보수정 페이지",
                'locale': "ko_KR",
                'type': "article",  # end common
                'date': False
            }
        )


def vote(request):
    '''
    [vote page]
    almost request & reply uesd ajax
    '''
    COUNTDOWN_TARGET_DATE = VoteDate.objects.get(pk=1).start_date
    DURIONG_DATE = VoteDate.objects.get(pk=1).end_date - VoteDate.objects.get(pk=1).start_date

    likes = Like.objects.filter(isVote=True)
    if COUNTDOWN_TARGET_DATE > timezone.now():
        return redirect('/index')
    elif (COUNTDOWN_TARGET_DATE + DURIONG_DATE) > timezone.now():
        td = (COUNTDOWN_TARGET_DATE + DURIONG_DATE) - timezone.now()
        send_data = (td.days * 86400) + td.seconds
        return render(
            request,
            "VoteApp/vote.html",
           {
               'active_home' : "active", # begin common
               'title' : "투표 진행 중!",
               'url' : "https://chenny.ml/",
               'description' : "LEE LAB 투표 진행중!",
               'sitename' : "Lee Lab Server",
               'locale' : "ko_KR",
               'type' : "article", # end common
               'noti_title' : "[종료 알림!!]", # begin noti
               'noti_context' : "투표가 종료되었습니다! 결과를 확인하세요!",
               'noti_img' : "https://chenny.ml/static/img/logo2.png", # end noti
               'date_of_begin_time' : "투표 종료일 : " + (COUNTDOWN_TARGET_DATE + DURIONG_DATE).strftime('%Y년 %m월 %d일 - %H시 %M분 %S초'),
               'server_time': send_data,
               'players' : likes,
               'all_member' : User.objects.count()-1
            }
        )
    else:
        return render(
            request,
            "VoteApp/vote.html",
           {
               'active_home' : "active", # begin common
               'title' : "투표 종료",
               'url' : "https://chenny.ml/",
               'description' : "LEE LAB 투표 결과",
               'sitename' : "Lee Lab Server",
               'locale' : "ko_KR",
               'type' : "article", # end common
               'date_of_begin_time' : "투표 종료일 : " + (COUNTDOWN_TARGET_DATE + DURIONG_DATE).strftime('%Y년 %m월 %d일 - %H시 %M분 %S초'),
               'server_time': 0,
               'players': likes,
               'all_member': User.objects.count()-1
            }
        )


def result(request):
    COUNTDOWN_TARGET_DATE = VoteDate.objects.get(pk=1).start_date
    DURIONG_DATE = VoteDate.objects.get(pk=1).end_date - VoteDate.objects.get(pk=1).start_date

    likes = Like.objects.annotate(like_count=Count('likes')).order_by('-like_count')
    if (COUNTDOWN_TARGET_DATE + DURIONG_DATE) > timezone.now():
        td = (COUNTDOWN_TARGET_DATE + DURIONG_DATE) - timezone.now()
        send_data = (td.days * 86400) + td.seconds
        return render(
            request,
            "VoteApp/result.html",
            {
                'active_home': "active",  # begin common
                'title': "투표 진행 중!",
                'url': "https://chenny.ml/",
                'description': "LEE LAB 투표 진행중!",
                'sitename': "Lee Lab Server",
                'locale': "ko_KR",
                'type': "article",  # end common
                'date_of_begin_time': "투표 종료일 : " + (COUNTDOWN_TARGET_DATE + DURIONG_DATE).strftime('%Y년 %m월 %d일 - %H시 %M분 %S초'),
                'server_time': send_data,
                'players': likes,
                'all_member': User.objects.count()-1,
                'result' : 'btn btn-warning disabled'
            }
        )
    else:
        return render(
            request,
            "VoteApp/result.html",
            {
                'active_home': "active",  # begin common
                'title': "투표 종료",
                'url': "https://chenny.ml/",
                'description': "LEE LAB 투표 결과",
                'sitename': "Lee Lab Server",
                'locale': "ko_KR",
                'type': "article",  # end common
                'date_of_begin_time': "투표 종료일 : " + (COUNTDOWN_TARGET_DATE + DURIONG_DATE).strftime('%Y년 %m월 %d일 - %H시 %M분 %S초'),
                'server_time': 0,
                'players': likes,
                'all_member': User.objects.count()-1,
                'result' : 'btn btn-info'
            }
        )


def capstone(request):
    '''
    [privacy policy page]
    page of privacy policy, just linked dev-favebook
    '''
    return render(
        request,
        "VoteApp/capstone_design.html",
        {
            'title' : "개인정보처리방침",
        }
     )

def signup(request):
    '''
    [signup page]
    this page is unsafe
    '''

Vote_of_LeeLab/VoteApp/templates/VoteApp/about.html
{% extends "VoteApp/layout.html" %}
{% block content %}
<section>
{% include "VoteApp/capstone_design.html" %}
</section>
{% endblock %}

Vote_of_LeeLab/VoteApp/templates/VoteApp/camera.html
{% extends "VoteApp/layout.html" %}
{% block content %}
    <section>

        <div class="alert alert-warning" role="alert">
            <p style="text-align: center">HTTP 연결에서 영상이 나타납니다. 만약 HTTPS 사용중이라면 상단에 있는 페이지 차단을 해제해 주세요.</p>
        </div>

        <div class="container">
            <iframe class="embed-responsive-item" src="{{ url }}" width="1300" height="750" scrolling="auto" allowfullscreen></iframe>
        </div>
    </section>
{% endblock %}

Vote_of_LeeLab/VoteApp/templates/VoteApp/candidate.html
{% extends "VoteApp/layout.html" %}
{% block content %}
    {% if date %}
        <section id="vote" class="container content">
            <div style="margin-bottom: 20px;"></div>
            <div class="row" style="text-align:center;">
                <div class="col-md-3"></div>
                <div class="alert alert-warning col-md-6" role="alert">
                    {% if result %}
                        <p style="text-align:center;">이 계정은 후보자 계정입니다. 시작일 전까지 정보 수정이 가능합니다.</p>
                    {% else %}
                        <p style="text-align:center;">이 계정은 후보자 계정이 아닙니다. 이 페이지를 이용할 수 없습니다.</p>
                    {% endif %}
                </div>
                <div class="col-md-3"></div>
            </div>
            {% if result %}
                <div class="row" style="text-align:center;">
                    <div class="col-md-2"></div>
                    <div class="alert alert-info col-md-68" role="alert">
                        <p style="text-align:center;">현재 이 계정에 설정된 정보는 다음과 같습니다..</p>
                        <hr/>
                        <p style="text-align:center;">후보자 이름 : {{ likes.name }}</p>
                        <p style="text-align:center;">후보자 소개 : {{ likes.description }}</p>
                    </div>
                    <div class="col-md-2"></div>
                    <div class="col-md-8">
                        <section id="loginForm">
                            <form action="{% url 'candidate' %}" method="post" class="form-horizontal">
                                {% csrf_token %}
                                <h4>수정할 수 있는 항목</h4>
                                <hr />
                                <div class="form-group">
                                    <label for="id_name_id" class="col-md-2 control-label">후보자 IDF</label>
                                    <div class="col-md-10">
                                        {#{{ form.name_id.value|default_if_none:likes.name_id }}#}
                                        {{ form.name_id }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_name" class="col-md-2 control-label">후보자 이름</label>
                                    <div class="col-md-10">
                                        {{ form.name }}
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="id_description" class="col-md-2 control-label">후보자 소개</label>
                                    <div class="col-md-10">
                                        {{ form.description }}
                                    </div>
                                </div>
                                <div class="form-group" style="text-align:left;">
                                    <div class="col-md-12" style="text-align: center">
                                        <input type="hidden" name="next" value="/" />
                                        <input id="submit" type="submit" value="저장" class="btn btn-default" />
                                    </div>
                                </div>
                            </form>
                        </section>
                    </div>
                    <div class="col-md-2"></div>
                </div>
            {% endif %}
        </section>

        <script type="text/javascript">
            $(document).ready(function () {
                $("select[id='id_name_id'] option").prop("disabled", true);
                $("select[id='id_name_id'] option:contains('{{ likes.name_id }}')").prop('selected', true).prop("disabled", true);
            });
            $(document).on("click", "#submit", function () {
                $("select[id='id_name_id'] option:contains('{{ likes.name_id }}')").prop('selected', true).prop("disabled", false);
            });
        </script>
    {% else %}
        <section id="vote" class="container content">
            <div style="margin-bottom: 20px;"></div>
            <div class="row" style="text-align:center;">
                <div class="col-md-3"></div>
                <div class="alert alert-danger col-md-6" role="alert">
                    <p style="text-align:center;">정보수정 가능 기간이 아닙니다.</p>
                </div>
                <div class="col-md-3"></div>
            </div>
        </section>
    {% endif %}
{% endblock %}

Vote_of_LeeLab/VoteApp/templates/VoteApp/countdown.html
<div class="pricing-section" style="padding-top:60px; padding-bottom:60px;">
    <div class="container">
        
        <!-- Start Call Action -->
        <div class="call-action call-action-boxed call-action-style1 clearfix">
            <!-- Call Action Button -->
            <h2 style="text-align:center;" class="primary">{{ date_of_begin_time }}</h2>
        </div>
        <!-- End Call Action -->
        
        <div class="alert alert-success" role="alert">
            <h4 style="text-align:center;" class="alert-heading">남은 시간 : <span style="margin-left:15px" id="day">--</span>일<span style="margin-left:15px" id="hour">--</span>시<span style="margin-left:15px" id="min">--</span>분<span style="margin-left:15px" id="sec">--</span>초</h4>
        </div>
{#        <div style="text-align:center; padding-bottom:25px;">#}
{#            {% if user.is_authenticated %}#}
{#            <button type="button" id="{{ likes }}" class="like btn btn-success glyphicon glyphicon-thumbs-up"> -</button>#}
{#            {% else %}#}
{#            <button type="button" id="{{ likes }}" class="like btn btn-success glyphicon glyphicon-thumbs-up disabled"> -</button>#}
{#            {% endif %}#}
{#        </div>#}
{#        {% if not user.is_authenticated %}#}
{#        <div class="col-md-3"></div>#}
{#        <div class="alert alert-warning col-md-6" role="alert">#}
{#            <p style="text-align:center;">로그인 후 <strong>좋아요!</strong> 혹은 <strong>싫어요!</strong> 버튼이 활성화 됩니다.</p>#}
{#        </div>#}
{#        <div class="col-md-3"></div>#}
{#        {% endif %}#}

    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var dday = {{ server_time }};
        {#var pk = {{ likes }};#}
        {#{% if user.is_authenticated %}#}
        {#$.ajax({#}
        {#    type: "POST",#}
        {#    url: "{% url 'like_ready' %}",#}
        {#    data: {#}
        {#        'pk': pk,#}
        {#        'csrfmiddlewaretoken': '{{ csrf_token }}'#}
        {#    },#}
        {#    dataType: "json",#}
        {#    success: function(response) {#}
        {#        $('#'+pk).text(' ' + response.message + ' ' + response.likes_count);#}
        {#    },#}
        {#    error: function(request, status, error) {#}
        {#        console.log("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);#}
        {#    }#}
        {# });#}
        {#{% else %}#}
        {#$.ajax({#}
        {#    type: "POST",#}
        {#    url: "{% url 'like_anonymous' %}",#}
        {#    data: {#}
        {#        'pk': pk,#}
        {#        'csrfmiddlewaretoken': '{{ csrf_token }}'#}
        {#    },#}
        {#    dataType: "json",#}
        {#    success: function(response) {#}
        {#        $('#'+pk).text(' ' + response.message + ' ' + response.likes_count);#}
        {#    },#}
        {#    error: function(request, status, error) {#}
        {#        console.log("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);#}
        {#    }#}
        {# });#}
        {#{% endif %}#}

        if (dday > 0) {
            var timer = setInterval(function () {
                if (dday == 0) {
                    notify();
                    location.reload();
                } else {
                    var rest = --dday;
                    var sec = rest % 60;
                    var min = ((rest - sec) / 60) % 60;
                    var hours = ((((rest - sec) / 60) - min) / 60) % 24;
                    var days = ((((((rest - sec) / 60) - min) / 60) - hours) / 24);

                    $("#sec").html((sec < 10) ? ('0' + sec) : sec);
                    $("#min").html((min < 10) ? ('0' + min) : min);
                    $("#hour").html((hours < 10) ? ('0' + hours) : hours);
                    $("#day").html((days < 10) ? ('0' + days) : days);
                }
            }, 1000);
        }
        else {
            clearInterval(timer);
        }
    });

{#    {% if user.is_authenticated %}#}
{#    $('.like').click(function() {#}
{#        var pk = $(this).attr('id');#}
{#        $.ajax({#}
{#            type: "POST",#}
{#            url: "{% url 'like' %}",#}
{#            data: {#}
{#                'pk': pk,#}
{#                'csrfmiddlewaretoken': '{{ csrf_token }}'#}
{#            },#}
{#            dataType: "json",#}
{#            success: function(response) {#}
{#                $('#'+pk).text(' ' + response.message + ' ' + response.likes_count);#}
{#            },#}
{#            error: function(request, status, error) {#}
{#                console.log("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);#}
{#            }#}
{#        });#}
{#    })#}
{#    #}
{#    {% endif %}#}
    function spawnNotification(title, body, icon) {
        var n = new Notification(title, {
            body: body,
            icon: icon
        });

        n.onclick = function (e) {
            e.preventDefault();
            window.open('{{ url }}', '_blank');
        }
    }
    
    function notify() {
        Notification.requestPermission().then(function (permission) {
            if (permission === 'granted') {
                spawnNotification('{{ noti_title }}', '{{ noti_context }}', '{{ noti_img }}');
            }
        });
    }
    
    window.addEventListener('load', function () {
        Notification.requestPermission(function (status) {
            if (Notification.permission !== status) {
                Notification.permission = status;
            }
        });
    });

</script >

Vote_of_LeeLab/VoteApp/templates/VoteApp/index.html
{% extends "VoteApp/layout.html" %}

{% block content %}
    <section id="countdown">
        {% include "VoteApp/countdown.html" %}
    </section>
{% endblock %}

Vote_of_LeeLab/VoteApp/templates/VoteApp/login.html
{% extends "VoteApp/layout.html" %}

{% block content %}
<section>
    <div class="row" style="text-align:center;">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <section id="loginForm">
                {% if user.is_authenticated %}
                <hr />
                <div class="alert alert-success" role="alert">
                    {{ user.last_name }}{{ user.first_name }}님은 {{ user.email }}로 로그인 하였습니다.
                </div>
                <hr />
                {% else %}
                <form action="." method="post" class="form-horizontal">
                    {% csrf_token %}
                    <h4>소셜 계정 혹은 로컬 계정으로 로그인</h4>
                    <hr />
                    {% if form.errors %}
                    <div class="alert alert-warning" role="alert">
                        아이디 혹은 비밀번호가 일치하지 않습니다. 다시 입력해 주세요.
                    </div>
                    <hr />
                    {% endif %}
                    <div class="form-group">
                        <label for="id_username" class="col-md-2 control-label">Username</label>
                        <div class="col-md-10">
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_password" class="col-md-2 control-label">Password</label>
                        <div class="col-md-10">
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group" style="text-align:left;">
                        <div class="col-md-12" style="text-align: center">
                            <input type="hidden" name="next" value="/" />
                            <input type="submit" value="로그인" class="btn btn-default" />
                        </div>
                    </div>
                </form>
                <a href="{% url "social:begin" "google-oauth2" %}"><button class="btn btn-danger fa fa-google-plus" style="width: 40%"> Google+ 로그인</button></a>
                <a href="{% url "social:begin" "facebook" %}"><button class="btn btn-primary fa fa-facebook-square" style="width: 40%"> Facebook 로그인</button></a>
                <!-- Old version
                <a href="{% url "social:begin" "facebook" %}?next={{ request.path }}"><button class="btn btn-primary fa fa-facebook-square" style="width: 40%"> Facebook 로그인</button></a>
                -->
                {% endif %}
            </section>
        </div>
        <div class="col-md-3"></div>
    </div>
</section>

{% load staticfiles %}
<script src="{% static 'js/jquery.validate.min.js' %}"></script>

{% endblock %}

Vote_of_LeeLab/VoteApp/templates/VoteApp/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Hello {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

Vote_of_LeeLab/VoteApp/templates/VoteApp/signup.html
{% extends "VoteApp/layout.html" %}

{% block content %}
<section>
    <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입" />
</form>
</section>
{% endblock %}